import course

COURSES = [
    course.Course(period=1,
                  name='Intro to Computer Science',
                  teacher_name='Ms. Lee',
                  resource_name='repl.it',
                  resource_url='https://repl.it/'),
    course.Course(period=2,
                  name='Ap Literature',
                  teacher_name='Mr. Wilson',
                  resource_name='sparknotes',
                  resource_url='http://www.sparknotes.com/'),
    course.Course(period=3,
                  name='Precalculus',
                  teacher_name='Ms.Chand',
                  resource_name='Khan Academy',
                  resource_url='https://www.khanacademy.org/math/precalculus'),
    course.Course(period=4,
                  name='Economics',
                  teacher_name='Mr.Seelbach',
                  resource_name='Investopedia',
                  resource_url='https://www.investopedia.com/terms/e/economics.asp'),
    course.Course(period=5,
                  name='Physics',
                  teacher_name='Mr.Trautman',
                  resource_name='Physics Classroom',
                  resource_url='http://www.physicsclassroom.com/'),
    course.Course(period=6,
                  name='Yearbook',
                  teacher_name='Mr.Barlas',
                  resource_name='Jostens',
                  resource_url='http://yearbookavenue.jostens.com/'),
    ]


import song

Top_Ten_Songs= [
    song.Song(title='Blood Sweat Tears',
              artist_name='BTS',
              youtube_url='https://www.youtube.com/watch?v=hmE9f-TEutc'),
    song.Song(title='Mic drop',
              artist_name='BTS',
              youtube_url='https://www.youtube.com/watch?v=kTlv5_Bs8aw'),
    song.Song(title='Bad Boy',
              artist_name='Red Velvet',
              youtube_url='https://www.youtube.com/watch?v=J_CFBjAyPWE'),
    song.Song(title='Starry Night',
              artist_name='Mamamoo',
              youtube_url='https://www.youtube.com/watch?v=0FB2EoKTK_Q'),
    song.Song(title='Peek-a-boo',
              artist_name='Red Velvet',
              youtube_url='https://www.youtube.com/watch?v=6uJf2IT2Zh8'),
    song.Song(title='In My Blood',
              artist_name='Shawn Mendes',
              youtube_url='https://www.youtube.com/watch?v=36tggrpRoTI'),
    song.Song(title='No Tears Left to Cry',
              artist_name='Ariana Grande',
              youtube_url='https://www.youtube.com/watch?v=ffxKSjUwKdU'),
    song.Song(title='Never Be Same',
              artist_name='Camila Cabello',
              youtube_url='https://www.youtube.com/watch?v=Ph54wQG8ynk'),
    song.Song(title='Likey',
              artist_name='Twice',
              youtube_url='https://www.youtube.com/watch?v=V2hlQkVJZhE'),
    song.Song(title='Ko Ko Bop',
              artist_name='Exo',
              youtube_url='https://www.youtube.com/watch?v=IdssuxDdqKk'),
]