import song

TOP_TEN_SONGS = [
    song.Song(title='Blood Sweat Tears',
              artist_name='BTS',
              youtube_url='https://www.youtube.com/watch?v=hmE9f-TEutc'),
    song.Song(title='Mic Drop',
              artist_name='BTS',
              youtube_url='https://www.youtube.com/watch?v=kTlv5_Bs8aw'),
    song.Song(title='Peek-A-Boo',
              artist_name='Red Velvet',
              youtube_url='https://www.youtube.com/watch?v=6uJf2IT2Zh8'),
    song.Song(title='Starry Night',
              artist_name='Mamamoo',
              youtube_url='https://www.youtube.com/watch?v=0FB2EoKTK_Q'),
    song.Song(title='Bad Boy',
              artist_name='Red Velvet',
              youtube_url='https://www.youtube.com/watch?v=J_CFBjAyPWE'),
    song.Song(title='Boombayah',
              artist_name='Black Pink',
              youtube_url='https://www.youtube.com/watch?v=bwmSjveL3Lc'),
    song.Song(title='Look',
              artist_name='Got7',
              youtube_url='https://www.youtube.com/watch?v=sS0LCjOiIhc'),
    song.Song(title='In My Blood',
              artist_name='Shawn Mendes',
              youtube_url='https://www.youtube.com/watch?v=36tggrpRoTI'),
    song.Song(title='No Tears Left To Cry',
              artist_name='Ariana Grande',
              youtube_url='https://www.youtube.com/watch?v=ffxKSjUwKdU'),
    song.Song(title='Likey',
              artist_name='Twice',
              youtube_url='https://www.youtube.com/watch?v=V2hlQkVJZhE'),
]